apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: scottyfops
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000