apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: scottyfops
spec:
  selector:
    app: my-app
  type: NodePort # Docker Desktop doesn't support LoadBalancer
  ports:
  - protocol: TCP
    port: 8080           # Port on which pod listens
    targetPort: 8080      # Target port in container
    nodePort: 30000       # External port for accessing service
