apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app
  namespace: scottyfops
spec:
  serviceName: "my-app-service"
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: scottyfops/assignment:v4
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "1100m"
        readinessProbe:
          exec:
            command: ["curl", "-sf", "http://probe-app.scottyfops.svc.cluster.local:30010/isAlive"]
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: data-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
